(function(){
  const API='../../api/admin/academic_admin.php';
  const categories={curriculum:'หลักสูตร',learning_area:'กลุ่มสาระ',curriculum_activity:'กิจกรรมหลักสูตร',subject_by_level:'รายวิชาตามระดับ',achievement_primary:'ผลสัมฤทธิ์ ป.1-ป.6',achievement_secondary:'ผลสัมฤทธิ์ ม.1-ม.6',onet:'O-NET',nt:'NT',graduation:'การสำเร็จการศึกษา'};
  const $=id=>document.getElementById(id); let items=[],csrf='';
  const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  function message(text,tone=''){const el=$('message');el.textContent=text;el.className=`form-message ${tone}`;}
  async function request(method='GET',body=null,url=API){const options={method,credentials:'same-origin',headers:{Accept:'application/json'}};if(body){options.headers['Content-Type']='application/json';options.headers['X-CSRF-Token']=csrf;options.body=JSON.stringify(body)}const response=await fetch(url,options);let data={};try{data=await response.json()}catch(e){}if(response.status===401){location.replace('../login.html');throw new Error('กรุณาเข้าสู่ระบบ')}if(response.status===403)throw new Error(data.error||'ไม่มีสิทธิ์ใช้งาน');if(!response.ok||data.success===false)throw new Error(data.error||'เกิดข้อผิดพลาด');return data}
  function fillSelects(){const options=Object.entries(categories).map(([v,l])=>`<option value="${v}">${l}</option>`).join('');$('category').innerHTML=options;$('filterCategory').insertAdjacentHTML('beforeend',options)}
  function filtered(){const y=$('filterYear').value,c=$('filterCategory').value,s=$('filterStatus').value,q=$('filterSearch').value.trim().toLowerCase();return items.filter(i=>(!y||i.academic_year===y)&&(!c||i.category===c)&&(!s||i.status===s)&&(!q||`${i.title} ${JSON.stringify(i.details)}`.toLowerCase().includes(q)))}
  function render(){const rows=filtered();$('tableBody').innerHTML=rows.length?rows.map((i,index)=>`<tr><td data-label="ลำดับ">${index+1} <button class="academic-action academic-order" data-action="up" data-id="${i.id}" title="เลื่อนขึ้น">↑</button><button class="academic-action academic-order" data-action="down" data-id="${i.id}" title="เลื่อนลง">↓</button></td><td data-label="หัวข้อ">${esc(i.title)}</td><td data-label="หมวดหมู่">${esc(categories[i.category]||i.category)}</td><td data-label="ปีการศึกษา">${esc(i.academic_year)}</td><td data-label="สถานะ"><span class="academic-status ${i.status}">${i.status==='published'?'เผยแพร่':'ฉบับร่าง'}</span></td><td data-label="วันที่แก้ไข">${esc(i.updated_at||'-')}</td><td data-label="จัดการ"><button class="academic-action academic-edit" data-action="edit" data-id="${i.id}">แก้ไข</button><button class="academic-action academic-delete" data-action="delete" data-id="${i.id}">ลบ</button></td></tr>`).join(''):'<tr><td colspan="7" class="academic-empty">ไม่พบข้อมูล</td></tr>'}
  function rebuildYears(){const current=$('filterYear').value;const years=[...new Set(items.map(i=>i.academic_year))].sort().reverse();$('filterYear').innerHTML='<option value="">ทุกปี</option>'+years.map(y=>`<option>${esc(y)}</option>`).join('');$('filterYear').value=current}
  async function load(){try{const data=await request();items=data.data||[];csrf=data.csrf_token||'';rebuildYears();render()}catch(e){message(e.message,'error')}}
  function open(item=null){$('academicForm').reset();$('itemId').value=item?.id||'';$('formTitle').textContent=item?'แก้ไขข้อมูลวิชาการ':'เพิ่มข้อมูลวิชาการ';const d=item?.details||{};$('title').value=item?.title||'';$('category').value=item?.category||'curriculum';$('academicYear').value=item?.academic_year||new Date().getFullYear()+543;$('status').value=item?.status||'draft';$('displayOrder').value=item?.display_order??0;$('level').value=d.level||'';$('description').value=d.description||'';$('items').value=(d.items||[]).join('\n');$('key').value=d.key||'';$('levelKey').value=d.level_key||'';$('shortLabel').value=d.short_label||'';$('scope').value=d.scope||'';$('entityKey').value=d.entity_key||'';$('value').value=d.value??'';$('value2').value=d.value2??'';$('editorModal').hidden=false;$('title').focus()}
  function close(){$('editorModal').hidden=true}
  function payload(){return{id:$('itemId').value?Number($('itemId').value):undefined,title:$('title').value,category:$('category').value,academic_year:$('academicYear').value,status:$('status').value,display_order:Number($('displayOrder').value),level:$('level').value,description:$('description').value,items:$('items').value,key:$('key').value,level_key:$('levelKey').value,short_label:$('shortLabel').value,scope:$('scope').value,entity_key:$('entityKey').value,value:$('value').value,value2:$('value2').value}}
  async function save(event){event.preventDefault();if(!$('academicForm').reportValidity())return;try{const editing=Boolean($('itemId').value);await request(editing?'PUT':'POST',payload());close();message(editing?'แก้ไขข้อมูลเรียบร้อยแล้ว':'เพิ่มข้อมูลเรียบร้อยแล้ว','success');await load()}catch(e){message(e.message,'error')}}
  async function remove(item){if(!confirm(`ยืนยันการลบ “${item.title}” หรือไม่? การดำเนินการนี้ย้อนกลับไม่ได้`))return;try{await request('DELETE',{id:Number(item.id)});message('ลบข้อมูลเรียบร้อยแล้ว','success');await load()}catch(e){message(e.message,'error')}}
  async function move(item,direction){const same=filtered().filter(i=>i.category===item.category&&i.academic_year===item.academic_year);const index=same.findIndex(i=>String(i.id)===String(item.id));const other=same[index+direction];if(!other)return;const a={...item,display_order:Number(other.display_order),...item.details};const b={...other,display_order:Number(item.display_order),...other.details};try{await request('PUT',a);await request('PUT',b);await load()}catch(e){message(e.message,'error')}}
  $('tableBody').addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const item=items.find(i=>String(i.id)===btn.dataset.id);if(!item)return;if(btn.dataset.action==='edit')open(item);if(btn.dataset.action==='delete')remove(item);if(btn.dataset.action==='up')move(item,-1);if(btn.dataset.action==='down')move(item,1)});
  ['filterYear','filterCategory','filterStatus'].forEach(id=>$(id).addEventListener('change',render));$('filterSearch').addEventListener('input',render);$('addBtn').addEventListener('click',()=>open());$('closeModal').addEventListener('click',close);$('cancelBtn').addEventListener('click',close);$('academicForm').addEventListener('submit',save);$('editorModal').addEventListener('click',e=>{if(e.target===$('editorModal'))close()});$('logoutBtn').addEventListener('click',async()=>{try{await fetch('../../api/admin/logout.php',{method:'POST',credentials:'same-origin'})}finally{location.replace('../login.html')}});fillSelects();load();
})();
